{% set name = "astro-datalab" %}
{% set version = "2.24.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/astro_datalab-{{ version }}.tar.gz
  sha256: e7dbcf806f1df4df2176f3e56c7f832ed2bec3a6c226a3ef7076bd61ce103fd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scipy >=1.11.3,<1.12.0
    - specutils >=1.13.0,<1.14.0
    - pyvo >=1.3,<1.4
    - pycurl-requests <0.6.0,>=0.5.0
    - numpy >=1.23.5,<1.26.4
    - matplotlib-base >=3.8.0,<3.9.0
    - httplib2 >=0.22.0,<0.23.0
    - pandas >=2.1.1,<2.2.0
    - astropy-base >=5.3.4,<5.4.0
    - chardet >=5.2.0,<5.3.0
    - requests >=2.31.0,<2.32.0
    - feedparser >=6.0.11,<6.1.0
    - pillow >=10.3.0,<10.4.0
    - pycurl >=7.45.3,<7.46.0
    - scikit-learn ==1.4.1.post1
    - mpl_animators <1.2.0
    - certifi

test:
  imports:
    - dl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astro-datalab/datalab/
  summary: Tools for interacting with NOIRLab's Astro Data Lab.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davner
